### ISSUE TITLE
Bug: org.openidentityplatform.commons.geo 21.0.0-SNAPSHOT FAILURE on building OpenIDM

### ISSUE THREAD

**Issue by jimmydevenportdxc** [OpenIdentityPlatform/OpenIDM#13]
**Describe the bug**
When following the latest instructions to build OpenIDM, this step fails:

mvn -DskipTests -Dmaven.javadoc.skip=true clean install -f OpenIDM/OpenICF/OpenDJ/forgerock-parent

ERROR "geolite.maxmind.com: Unknown host"

**To Reproduce**
1. Go to https://github.com/OpenIdentityPlatform/OpenIDM
2. Scroll down to How to Build
3. Run step 1 for the git clone
4. Run step for mvn -DskipTests -Dmaven.javadoc.skip=true clean install -f OpenIDM/OpenICF/OpenDJ/forgerock-parent
5. mvn fails with the "[ERROR] Failed to execute goal com.savage7.maven.plugins:maven-external-dependency-plugin:0.6-SNAPSHOT:resolve-external (resolve-install-external-dependencies) on project geo: geolite.maxmind.com: Unknown host geolite.maxmind.com -> [Help 1]"

**Expected behavior**
mvn command should complete successfully

**Desktop (please complete the following information):**
 - OS: Red Hat Enterprise Linux 8
- Java: openjdk version "1.8.0_262"
- Maven: Apache Maven 3.5.4 (Red Hat 3.5.4-5)

**Comment by jingkang99** [comment]
encountered same issue today, the reason is the download url not existing anymore.

Solution:
register an account at maxmind.com and get 2 files
GeoLite2-ASN.tar.gz GeoLite2-City.tar.gz

mkdir -p download/geoip/database
put those 2 files in database folder

add an entry in /etc/hosts, your IP
10.0.0.x    geolite.maxmind.com

python3  -m http.server 80

so let the mvn and pom.xml download the 2 necessary files

Cheers!

**Comment by vharseko** [comment]
fixed from https://github.com/OpenIdentityPlatform/OpenIDM/commit/c3f325788d5bf254e240a06adc581484be3467fc
